Adding Pocket signup CTA to new tab learn more page
mozmeao/pocket-marketing-pages pull request #19
Opened 2021-06-03 23:02 UTC by slightlyoffbeat

2021-06-08 17:27 UTC, craigcook requested changes
Looks good, just a few minor nitpicks. The most significant issue is that I think the hero image should probably be served locally and not from bedrock. Though if it's going to be short-lived (is this just an experiment?), and if mozilla.org is allowed as an image host, it's probably fine.

2021-06-08 17:27 UTC, craigcook commented on content/marketing-assets/page/new_tab_learn_more/style.css
> +  font-family: Graphik Web, Helvetica Neue, Helvetica, Arial, Sans-Serif;
multi-word font names should be quoted:
```suggestion
  font-family: "Graphik Web", "Helvetica Neue", Helvetica, Arial, Sans-Serif;
```

2021-06-08 17:27 UTC, craigcook commented on content/en/firefox/new_tab_learn_more/index.html
> +            <img src="https://www.mozilla.org/media/cro_exp/img/getpocket/pocket-list-v2.png" alt="meh" />
This image should probably be added locally instead of served from www.mozilla.org. I'm not sure of the CSP settings for getpocket.com, it may not work in production if mozilla.org isn't allowed as an image host. But more importantly it creates an external dependency and if we were to delete the image from bedrock this page could break without anyone knowing.

I also notice this screenshot is the outdated, pre-Proton UI, but it may not be in scope to update it right now.

2021-06-11 03:18 UTC, slightlyoffbeat commented on content/en/firefox/new_tab_learn_more/index.html
> +            <img src="https://www.mozilla.org/media/cro_exp/img/getpocket/pocket-list-v2.png" alt="meh" />
Image is now local which will just add it to the s3 bucket which should work for now. (and alt tag fixed)

Good call on the UI, but it should be fixed separately from this PR.

2021-06-11 03:20 UTC, slightlyoffbeat commented
@craigcook changes added. Let me know if this look good to go now.

2021-06-11 15:54 UTC, craigcook approved these changes

2021-06-11 15:55 UTC, craigcook commented
Looks good, but it's still marked "do not merge" so I don't want to click the button if there's some reason we need to wait. Feel free to merge when ready.

2021-06-11 16:49 UTC, merged